import "./globals.css";

export const metadata = {
  title: "Bundle Analytics",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      style={{
        fontFamily: 'sans-serif'
      }}
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
